### ISSUE TITLE
Component ECS for Items

### ISSUE THREAD

**Issue by zoubirabde9a** [kk-digital/kcg#141] opened 2022-05-27 16:40 UTC
Make the following
- Item/ItemList.cs
- Item/ItemEntity.cs
- Item/ItemDrawSystem.cs //draw system
- Item/ItemPhysicsSystem.cs
- Item/ItemComponents/

- Put inventory system here? Later, after its already in agents

**Comment by mororo250** [comment] 2022-06-08 10:13
Duplicate of #206

**Closed by mororo250** 2022-06-08 10:13 UTC
