### ISSUE TITLE
Port tool bar and gui

### ISSUE THREAD

**Issue by zoubirabde9a** [kk-digital/kcg#181] opened 2022-06-01 19:14 UTC
- port GUI for tool bar: like minecraft/terraria
you have 10 items and one of them is highlighted and ready to use
an example of that is the tile placement tool, where you can place tiles on the map.

- port gui health bar from cx-game

**Comment by mororo250** [comment] 2022-06-08 06:19
Hi, how's this going?

**Comment by mororo250** [comment] 2022-06-08 06:21
Duplicate of #208?

**Comment by choi303** [comment] 2022-06-08 07:51
> Hi, how's this going?

Didn't start yet. You can take over if you want. You have more knowledge about inventory.

**Comment by mororo250** [comment] 2022-06-08 09:38
this would be great @choi303 choi

**Comment by choi303** [comment] 2022-06-08 09:39
> this would be great @choi303

Okay than.

**Comment by mororo250** [comment] 2022-06-13 09:45
Missing health bar.
Someone else can do it.

**Closed** 2022-06-14 07:13 UTC
